### ISSUE TITLE
Find recipes available with pantry

### ISSUE THREAD

**Issue by montgomerysamantha** [dkhwang118/CIS560_F18-Project-RecipeManager#1]

**Comment by dbramucci** [comment]
As of Commit [a6ceb5ae4d8ec7307c40cd2447719f8a5d3505b6](https://github.com/dkhwang118/CIS560_F18-Project-RecipeManager/commit/a6ceb5ae4d8ec7307c40cd2447719f8a5d3505b6) I've added the ability to read ingredients and recipes from the database.

What still needs to be done is to find the recipes that can be produced from a given pantry.
