### ISSUE TITLE
Stub out the gui

### ISSUE THREAD

**Issue by dbramucci** [dkhwang118/CIS560_F18-Project-RecipeManager#11]
Make the GUI such that it depends on methods with the same type-signature as the back-end methods will have, and then make a functional gui from that.

Finally, update the stubs to instead use the back-end SQL query methods instead.

**Comment by laurel-thomson** [comment]
I have the QueryStub completed.  Once the Query partial classes are completed, we'll just create a Query class in the HomeController instead of a QueryStub.  I'm going to close out this issue, because a separate issue has been created for each UI.
