### ISSUE TITLE
Create partial Query classes implement the method declarations of IQuery

### ISSUE THREAD

**Issue by laurel-thomson** [dkhwang118/CIS560_F18-Project-RecipeManager#23]

**Comment by dkhwang118** [comment]
I added a new dev branch for this and will begin working on the methods. I have created "Query_TEST.cs" as a class that now holds the methods still needing to be implemented (for placeholder purposes only; later to be deleted), and will start with "CreateRecipe()" and work my way down the list (unless someone already had a good idea of how to implement this method, in which case I will just start on the next on the list). Anyone that wants to join in, please feel free!
