### ISSUE TITLE
What new methods do we need to manage Shopping Lists properly in the DB

### ISSUE THREAD

**Issue by dbramucci** [dkhwang118/CIS560_F18-Project-RecipeManager#36]
Currently, we can only create a shopping list by finding the one needed to make some recipes.

**Comment by dbramucci** [comment]
* Modify Quantities
* Add ingredients to the list
* Create an new (empty) Shopping List

**Comment by laurel-thomson** [comment]
As of our discussion yesterday, at this point we're not going to worry about creating empty Shopping Lists and adding Ingredients to the list apart from those in the Recipe.

**Comment by laurel-thomson** [comment]
We still need a "Shop" query to modify Ingredient Quantities (#64)
