### ISSUE TITLE
Add a new Stats Form to display reports

### ISSUE THREAD

**Issue by laurel-thomson** [dkhwang118/CIS560_F18-Project-RecipeManager#49]
This form should display reports about the recipes.  It should display the data from the report-style queries we are going to write (#37 )

**Comment by dkhwang118** [comment]
I've begun working on the stats page in the STATS_GUI_Dev branch. My plan is to try to copy the style of the current GUI implementation for the other forms as much as possible, but if anyone wants to join in, help is always welcome and appreciated.

**Comment by dkhwang118** [comment]
Basic Stats Form implementation. Could use more work in displaying the results, but will work for the presentation. Merged into master on 12/2/2018
