### ISSUE TITLE
When a Recipe is rated, the DGV doesn't update with the new rating

### ISSUE THREAD

**Issue by laurel-thomson** [dkhwang118/CIS560_F18-Project-RecipeManager#57]
The rating is saved in the database and in the Recipe object, but the DGV doesn't refresh with the new rating unless the form is closed and reopened.

**Comment by dkhwang118** [comment]
Just pushed a small code change to fix this using the same check/update method called when the user checks the AvailableRecipes checkbox. Perhaps the code may not be in the right place, but it is a quick fix to get rid of the issue. 

Keeping the issue open just-in-case the change is not implemented correctly (e.g. update calls should happen in a different form than the one I added to).

**Comment by laurel-thomson** [comment]
Works for me!
