### ISSUE TITLE
If a Recipe is created without ingredients, after closing program, cannot reopen.

### ISSUE THREAD

**Issue by dkhwang118** [dkhwang118/CIS560_F18-Project-RecipeManager#58]
The exception is thrown within the ReadRecipe method, as no lines are returned for the ingredient lookup of the non-ingredient-holding Recipe. Should just be a simple fix by adding a check to make sure users have added ingredients while building a Recipe. Question is, should we actually allow a recipe with no ingredients to be created successfully?

**Comment by laurel-thomson** [comment]
I feel that we shouldn't allow them to create a Recipe without ingredients.

**Comment by laurel-thomson** [comment]
I added a quick fix to check if the Ingredients list if empty in the GUI.
